server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bbs?serveTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: limelight
      password:

mybatis-plus:
  global-config:
    db-config:
      table-prefix: bbs_
      id-type: auto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
